# Generated by Django 3.0.2 on 2020-01-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ways', '0003_auto_20200122_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
