# Generated by Django 3.0.2 on 2020-01-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ways', '0004_auto_20200122_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passwordbfa',
            field=models.CharField(default='ccccccc', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passwordotp',
            field=models.CharField(default='bbbbbb', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
