# Generated by Django 3.0.2 on 2020-01-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ways', '0005_auto_20200122_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
