# Generated by Django 3.0.2 on 2020-01-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ways', '0006_auto_20200122_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
