# Generated by Django 3.0.2 on 2020-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ways', '0007_auto_20200122_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_name', models.CharField(max_length=64, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
